workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - appstore_credentials      # APP_STORE_CONNECT_KEY_IDENTIFIER
                                     # APP_STORE_CONNECT_ISSUER_ID
                                     # APP_STORE_CONNECT_PRIVATE_KEY
        - certificate_credentials   # CERTIFICATE_PRIVATE_KEY
      vars:
        BUNDLE_ID: "com.coupleclarity.app"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        APP_STORE_APP_ID: 6759870857
      xcode: latest
      node: 18
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up keychain for code signing
        script: keychain initialize

      - name: Fetch signing files from App Store Connect
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Install npm dependencies
        script: npm install --include=dev

      - name: Build web assets
        script: npm run build

      - name: Sync Capacitor iOS project
        script: npx cap sync ios

      - name: Install CocoaPods dependencies
        script: cd ios/App && pod install

      - name: Set up code signing on Xcode project
        script: xcode-project use-profiles

      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR/ios/App
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APP_ID" || echo 0)
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))

      - name: Build IPA for distribution
        script: |
          cd $CM_BUILD_DIR/ios/App
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/App/build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
      email:
        recipients:
          - charles@barmorecpa.com
        notify:
          success: true
          failure: true
